@startuml
!theme plain
left to right direction
skinparam componentStyle uml2
skinparam nodesep 20
skinparam ranksep 150

together {
  component [api] as api
  component [redis] as redis
}

api -[hidden]r- redis

' --- Port definitions ---

component redis {
    portin "commands" as redis_commands
}

' --- Connections ---

api -[dotted]-> redis_commands : "Redis 74 key pattern(s); commands: DEL, EXEC, EXISTS, GET, INCR, KEYS, MULTI, SET, SETEX, ZADD, ZRANGEBYSCORE, ZSCORE"
@enduml
