@startuml
!theme plain
left to right direction
skinparam componentStyle uml2
skinparam nodesep 20
skinparam ranksep 150

together {
  component [nest-server] as nest_server
  component [redis] as redis
}

nest_server -[hidden]r- redis

' --- Port definitions ---

component redis {
    portin "commands" as redis_commands
}

' --- Connections ---

nest_server -[dotted]-> redis_commands : "Redis 28 key pattern(s); commands: DEL, GET, KEYS, SET"
@enduml
