@startuml
!theme plain
left to right direction
skinparam componentStyle uml2
skinparam nodesep 20
skinparam ranksep 150

together {
  component [gateway] as gateway
  component [mailer] as mailer
  component [permission] as permission
  component [task] as task
  component [token] as token
  component [user] as user
}

gateway -[hidden]r- mailer
mailer -[hidden]r- permission
permission -[hidden]r- task
task -[hidden]r- token
token -[hidden]r- user

' --- Port definitions ---

component mailer {
    portin "/mailer/mail_send" as mailer_mailer_mail_send
}

component permission {
    portin "/permission/permission_check" as permission_permission_permission_check
}

component task {
    portin "/task/task_create" as task_task_task_create
    portin "/task/task_delete_by_id" as task_task_task_delete_by_id
    portin "/task/task_search_by_user_id" as task_task_task_search_by_user_id
    portin "/task/task_update_by_id" as task_task_task_update_by_id
}

component token {
    portin "/token/token_create" as token_token_token_create
    portin "/token/token_decode" as token_token_token_decode
    portin "/token/token_destroy" as token_token_token_destroy
}

component user {
    portin "/user/user_confirm" as user_user_user_confirm
    portin "/user/user_create" as user_user_user_create
    portin "/user/user_get_by_id" as user_user_user_get_by_id
    portin "/user/user_search_by_credentials" as user_user_user_search_by_credentials
}

' --- Connections ---

gateway -[dashed]-> permission_permission_permission_check : "gRPC permission_check"
gateway -[dashed]-> task_task_task_create : "gRPC task_create"
gateway -[dashed]-> task_task_task_delete_by_id : "gRPC task_delete_by_id"
gateway -[dashed]-> task_task_task_search_by_user_id : "gRPC task_search_by_user_id"
gateway -[dashed]-> task_task_task_update_by_id : "gRPC task_update_by_id"
gateway -[dashed]-> token_token_token_create : "gRPC token_create"
gateway -[dashed]-> token_token_token_decode : "gRPC token_decode"
gateway -[dashed]-> token_token_token_destroy : "gRPC token_destroy"
gateway -[dashed]-> user_user_user_confirm : "gRPC user_confirm"
gateway -[dashed]-> user_user_user_create : "gRPC user_create"
gateway -[dashed]-> user_user_user_get_by_id : "gRPC user_get_by_id"
gateway -[dashed]-> user_user_user_get_by_id : "gRPC user_get_by_id"
gateway -[dashed]-> user_user_user_search_by_credentials : "gRPC user_search_by_credentials"
user -[dashed]-> mailer_mailer_mail_send : "gRPC mail_send"
@enduml
