@startuml
!theme plain
left to right direction
skinparam componentStyle uml2
skinparam nodesep 20
skinparam ranksep 150

together {
  component [gateway] as gateway
  component [mailer] as mailer
  component [permission] as permission
  component [task] as task
  component [token] as token
  component [user] as user
}

gateway -[hidden]r- mailer
mailer -[hidden]r- permission
permission -[hidden]r- task
task -[hidden]r- token
token -[hidden]r- user

' --- Port definitions ---

component mailer {
    portin "1 RPC endpoint(s)" as mailer_1_RPC_endpoint_s
}

component permission {
    portin "1 RPC endpoint(s)" as permission_1_RPC_endpoint_s
}

component task {
    portin "4 RPC endpoint(s)" as task_4_RPC_endpoint_s
}

component token {
    portin "3 RPC endpoint(s)" as token_3_RPC_endpoint_s
}

component user {
    portin "4 RPC endpoint(s)" as user_4_RPC_endpoint_s
}

' --- Connections ---

gateway -[dashed]-> permission_1_RPC_endpoint_s : "gRPC PERMISSION_CHECK"
gateway -[dashed]-> task_4_RPC_endpoint_s : "gRPC TASK_CREATE, TASK_DELETE_BY_ID, TASK_SEARCH_BY_USER_ID, TASK_UPDATE_BY_ID"
gateway -[dashed]-> token_3_RPC_endpoint_s : "gRPC TOKEN_CREATE, TOKEN_DECODE, TOKEN_DESTROY"
gateway -[dashed]-> user_4_RPC_endpoint_s : "gRPC USER_CONFIRM, USER_CREATE, USER_GET_BY_ID, USER_SEARCH_BY_CREDENTIALS"
user -[dashed]-> mailer_1_RPC_endpoint_s : "gRPC MAIL_SEND"
@enduml
